stages:
  - build
  - test
  - docker

variables:
  DOCKER_IMAGE: lisapp
  DOCKER_TAG: latest

# -----------------------------
# Stage 1: Build .NET projects
# -----------------------------
build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - echo "Restoring dependencies..."
    - dotnet restore LongestIncreasingSubset/LongestIncreasingSubset.csproj
    - echo "Building main project..."
    - dotnet build LongestIncreasingSubset/LongestIncreasingSubset.csproj -c Release
  only:
    - master

# -----------------------------
# Stage 2: Run tests
# -----------------------------
test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - echo "Running unit tests..."
    - dotnet test LISTest/LISTest.csproj --configuration Release --no-build --verbosity normal
  only:
    - master

# -----------------------------
# Stage 3: Build Docker image and push
# -----------------------------
docker_build:
  stage: docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - echo "Pushing Docker image..."
    - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
    - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
  only:
    - master